### ISSUE TITLE
Own ApplicationNumber to be sent

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ApplicationPattern#160]
Every application will have an application number.  
UUIDs of TcpClients, HttpClients and OperationClients will be formulated based on the application-number.  
How should the application, which is addressed by a subscription know the ApplicationNumber, which is to be used in the UUIDs of the TcpClient, HttpClient and OperationClient for the notifications?

Proposal:
The own ApplicationNumber shall be documented in an additional ApplicationNumber attribute in the HttpServer of every application and it shall be send instead of the ApplicationName in the originator field of every header.

**Comment by PrathibaJee** [comment]
1. Documenting the ApplicationNumber as an attribute in the HttpServer capability is the best solution. Thanks for the proposal.
2. Regarding the originator field , can we have a combination of  **"ApplicationNumber" + ":"+ "ApplicationName"**. 
The reason for this ask is , in the EaTL , 
        - when we look at the trace logs , 
        - if originator field has  "ApplicationName" , 
        - it will make the job easy to identify the originator.
Kindly let me know your views.

**Comment by openBackhaul** [comment]
If we would want to keep the ApplicationName in the header, we could probably add an additional parameter (but should separate name and number).

**Comment by openBackhaul** [comment]
**Alternative Proposal:**  
What would be pros/cons of changing the format of the UUIDs by replacing the ApplicationNumber by the abbreviation of the ApplicationName plus the ReleaseNumber.  

Example: _ro-0-0-1-http-c-0040_    ---->    _ro-0-0-1-http-c-0-eatl-1-0-0-0_

Storing:  
All existing ApplicationName attributes would be used for storing the abbreviation of the ApplicationName instead. (Full name of the application would no longer occur in the data.)  

Transporting:  
The originator field in the header would be used for transporting the abbreviation of the ApplicationName plus the ReleaseNumber.  

Example: _TypeApprovalRegister_    ---->    _tar-1-0-0_

**Comment by PrathibaJee** [comment]
Kindly please find the below details for the Alternate Proposal mentioned in the previous [comment ](https://github.com/openBackhaul/ApplicationPattern/issues/160#issuecomment-1194291219)

### **UUID :**
**Pros:**
This new uuid format ,
1. will help us to understand the underlying ltp instance easily.
2. looks less complex to model than the existing one.

**Note:**
**Also this point will be applicable to the existing uuid format** 
As of now, in our arichitecture , only a single instance of an application will run. In future ,  if we want to run two instance of a same application(with same version) , then we need to extend this format to support more instances.

### **Storing :**
Kindly please correct me if my understanding is wrong , 
In the http-client/server “application-name” will be represented by their abbreviation, 
Instead of this, 
```
{
  "application-name": "TypeApprovalRegister"
}
```
this will be there,
```
{
  "application-name": "TAR"
}
```

If we store the abbreviation alone and not the full application name , then to figure out an application's purpose we have to refer the corresponding application’s “purpose” details in their “inform-about-application”.
Considering if we have 30 to 35 applications , then figuring out an application's purpose from the abbreviation will become little difficult. A full application name will help us to guess an application's purpose than the abbreviation.

**Alternate proposal for storing :**
All the full application names are **upper camel case**.
Can we store the application-name as full , and from the uppercase letters in the application-name can we  generate the new uuid format.
Kindly let me know your views.

### **Transporting** :

Regarding the “originator” header , 
For example , if we take the flow from "register-application to update-approval-status" , 

1.	register-application **from CurrentController** 
        **originator : CurrentController**
2.	regard-application **from RegistryOffice** to TypeApprovalRegister
        **originator : RegistryOffice**
4.	update-approval-status **from TypeApprovalRegister** to RegistryOffice 
        **originator : TypeApprovalRegister**

This current purpose of the originator is useful for us to trace the **source and destination of a flow** in the EaTL application.

**Alternate proposal for Transporting:**
Usually , a http-client instance will be initiated when an application is regarded with a new application information.
As a part of all regard-application service , we have the "application-name" and "release-number" field. 
Can we use this fields(along with the alternate proposal for storing) to generate the new uuid format. 
Kindly let me know your views.

**Comment by openBackhaul** [comment]
I agree on 
- using uppercase letters in the application-name for deriving the abbreviation, which is used in the UUID, 
- using the existing "application-name" and "release-number" fields.

**Comment by openBackhaul** [comment]
**Summary of changes that are necessary for modifying the format of the UUID from for Example ro-0-0-1-http-c-0040 ----> ro-0-0-1-http-c-0-eatl-1-0-0-0:**
- Documentation about [Structure of UUIDs](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/StructureOfUuids/StructureOfUuids.md)
ApplicationPattern:
- ServiceList
- ProfileList
- ProfileInstanceList
- ForwardingList
- many cases of OAS :: example :: uuid:
- many cases of OAS :: example :: client-ltp:
- many cases of OAS :: example :: server-ltp:
- OAS :: /v1/update-operation-key :: requestBody :: operation-uuid :: pattern
- OAS :: /core-model-1-4:control-construct :: responses :: uuid :: pattern
- for all paths on OaM layer :: parameters :: uuid :: pattern & example
- CONFIGfile
- Testcases
All other Applications same thing

**Comment by openBackhaul** [comment]
Pull-request under review.
