### ISSUE TITLE
fc ServiceRequestCausesFcPortUpdateRequest (/v1/update-fc-port) needs update in load-file and forwarding definition

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#240]
As per understanding, the service /v1/update-fc-port will be called when there is an update in already existing fc-port instance 
Example: when the logical-termination-point attribute of an already existing fc-port of local-id "xxx" is updated with new value.
This happens in following scenarios:
1. In forwarding-constructs, which has the OUTPUT port to be a single persistent client instance and is allowed only for over-writing instead of creating a new OUTPUT port.
       _Example_: PromptForRegisteringCausesRegistrationRequest (when /v1/register-application is replaced by new operation-name through /v1/register-yourself)
3. If an application's operation-client LTP is already mapped to a forwarding-construct, and when it is replaced by a new operation-client instance. In this case, the already mapped fc-port will be updated only for logical-termination-point.
      _Example_: TypeApprovalCausesRequestForEmbedding (when a new operation-name comes for already registered application)

Problem statement:
The services which are applicable for the above scenarios are not mentioned in the initial load-file and in the ApplicationPattern+forwardings file

Below is an analysis made on the basic services that could enable /v1/update-fc-port forwarding to ALT based on above scenarios

|Application Pattern|                      /v1/update-fc-port|
|:----|:----|
|/v1/register-yourself|PromptForRegisteringCausesRegistrationRequest|
|/v1/embed-yourself|PromptForBequeathingDataCausesRequestForBroadcastingInfoAboutServerReplacement, PromptForBequeathingDataCausesRequestForDeregisteringOfOldRelease, PromptingNewReleaseForUpdatingServerCausesRequestForBroadcastingInfoAboutBackwardCompatibleUpdateOfOperation|
|/v1/redirect-service-request-information|ServiceRequestCausesLoggingRequest|
|/v1/redirect-oam-request-information|OamRequestCausesLoggingRequest|
|/v1/inquire-oam-request-approvals|OamRequestCausesInquiryForAuthentication|
|/v1/redirect-topology-change-information|PromptForRedirectingTopologyInformationCausesSendingAnInitialStateToALT, ServiceRequestCausesLtpUpdateRequest, ServiceRequestCausesLtpDeletionRequest, ServiceRequestCausesFcUpdateRequest, ServiceRequestCausesFcPortUpdateRequest, ServiceRequestCausesFcPortDeletionRequest, OamRequestCausesLtpUpdateRequest, OamRequestCausesLtpDeletionRequest, OamRequestCausesFcUpdateRequest, OamRequestCausesFcPortUpdateRequest, OamRequestCausesFcPortDeletionRequest

**Comment by openBackhaul** [comment]
The word "update" is used in service names for either changing an existing or creating a new instance of something.
This might have lead to a misunderstanding in case of /v1/update-fc-port.  

Basically, an FcPort is a reference on an LTP.
So, an FcPort is only changing, if the reference gets re-directed from one LTP to another.
In cases the values inside an LTP are changing, the FcPort usually don't changes.  

Example: /v1/register-yourself
Even if the name of the registration-operation gets updated, it is assumed that the OperationClient towards the RegistryOffice is already existing in the original CONFIGfile. So, no new LTP and no update of the FcPort.

Same for the rest of cases listed in the table above.

But ...
changes on the FcPorts are to be expected in case of subscriptions.

**/v1/end-subscription should have a callback towards /v1/delete-ltp-and-dependents.**
(No dedicated call of /v1/delete-fc-port, because /v1/delete-ltp-and-dependents is already including deleting the FcPorts, too.)

Further requests for subscribing are not included in the ApplicationPattern, but in the individual applications.
(Availability of the necessary callbacks to the ApplicationLayerTopology should be double checked there.)

**Comment by openBackhaul** [comment]
After implementing changes described in issue #284, FC and FcPort are kept unchanged in the cases described in [this issue](https://github.com/openBackhaul/ApplicationPattern/issues/240#issue-1334719012). => no change required.  

Missing callback indicated in [comment above]( https://github.com/openBackhaul/ApplicationPattern/issues/240#issuecomment-1250112263) has actually to trigger /v1/delete-fc-port and will be tracked in issue #285. => change tracked somewhere else.

If callbacks would be missing in individual subscriptions of applications, issues would be opened in the respective repositories. => potential changes tracked somewhere else.
