### ISSUE TITLE
Delegating role-based User Authorisation to the upper layer applications, will this cover our future needs? 

### ISSUE THREAD

**Issue by alattoch** [openBackhaul/ApplicationPattern#263]
Today the Applications will be authorised by Registration Office (RO). After approval the OKM will guaranty that the client application is allowed to consume service from the server site application.
The user management based on specific rules **is expected to be handled in the external client application** (not in scope of Tiny-Application-Controller).  

Do we need to prepare something in the today Tiny Application Controller? Or would it be sufficient that the application owner defines individualised service reflecting those roles. Let us agree how to mange this separation of how can what service at the individual part.

e.g. The FirmwareManagementApplication is able: 
1. provide current Firmware version 
    ==>Read only 
    ==>will require read access at the SDN Controller
2. make backup of the current running configuration 
   ==> write operation with low risk 
   ==> will require write access at the SDN Controller
4. uploading new Firmware => Write operation with low risk
   ==> write operation with low risk 
   ==> will require write access at the SDN Controller
6. activation on new Firmware  
   ==> Write operation with very high risk
   ==> will require write access at the SDN Controller

**Comment by alattoch** [comment]
[220826 discussion slides .pptx](https://github.com/openBackhaul/ApplicationPattern/files/9432418/220826.discussion.slides.002.pptx)

**Comment by alattoch** [comment]
If own UAM would be needed, we need to regard.
1. One Trust Create one Data processing directory 
2. Deletion Concept / Time & Potentially Event triggered
3. DPA for MS Operation, MS Development partners

**Comment by openBackhaul** [comment]
The TinyApplicationController is for managing applications.

The individual applications could be made for managing firmware, capacity licenses, radio frequencies and much more.
How could the TinyApplicationController know which user of an application would be allowed to execute these diverse tasks?
The TinyApplicationController would be the wrong place for managing user rights on diverse activities in the transport network.

A header with description "personalized user" (in the slides) seems to be contradicting the lately raised question for compliance with German data protection law.

According to initial design, user management must be implemented in the software, which is providing the user interface.
I can't understand an alternative solution from the provided slides or additional comment.

If several different software for user interfacing with operational personnel would be planned, it could be considered whether having a separate REST server for authenticating operational personnel (alike the AdministratorAdministration) would make sense.

But independently from that question, managing individual application users seems not to be part of the ApplicationPattern or TinyApplicationController. If so, withdrawing (closing) the issue would be appreciated.

**Comment by alattoch** [comment]
The user management UAM was just for explaining the context and not concrete request for implementation. 

Before closing this issue, could we please clarify the two questions here:
->Why are we processing the user-name with in the http header?  Would it be sufficient if we use it for communication with AdministratorAddministration?
->Can we avoid storing the user-name (except for AA)?

**Comment by openBackhaul** [comment]
You closed the issue three days ago.

> Why are we processing the user-name with in the http header? 
We don't _process_ the user-name from the header yet. 
There is just a field in the header that allows transporting it, because it is _mandatory_ according to the gctio _"Microservice Framework Reference Model v1.1"_.
The only _processing_ actually applied on the value in this field is storing it in the EaTL records.

> Would it be sufficient if we use it for communication with AdministratorAddministration?
It would not make sense to use it for communicating with AdministratorAddministration, because the AdministratorAddministration authenticates persons, who are configuring applications, and the user-name field in the header allows transporting the name of persons, who potentially try to configure network elements.
It's different purposes.

> Can we avoid storing the user-name (except for AA)?
Certainly, we can avoid, respectively even prevent storing the user-name value from technical point of view (e.g. by deleting the field from the header definition).
As far as I remember, it is task in issue #258 to synchronize operational needs within the limitations by German data protection rules.
