### ISSUE TITLE
AP implementation: application-name attribute update on "find or create"

### ISSUE THREAD

**Issue by MartinSunal** [openBackhaul/ApplicationPattern#300]
Whenever additionally the description of the application-name field start with “find or create”,
the http-client/application-name that connects to the mapped forwardingConstruct must be updated to the incoming application’s name
Examples:
- /v1/redirect-topology-change-information
- /v1/register-yourself
- /v1/embed-yourself

If the description starts with "find or create" , then if the incoming application-name does'nt match the http-client/application-name that connects to the mapped forwardingConstruct , the http-client/application-name will be updated based on the incoming request.

If the referenced httpClient would not yet exist, it could even be created with the stated uuid, but in almost all cases it is an update of the httpClient that already got defined in the CONFIGfile before instantiation of the application.

Discussed in https://github.com/openBackhaul/ApplicationPattern/issues/92
Depends on adopting of changes by applications made in [Add PUT to OAM of application-name](https://github.com/openBackhaul/ApplicationPattern/pull/296).

**Comment by openBackhaul** [comment]
@MartinSunal:  
Could you please analyze, whether the referenced issues and pull-requests are completely solving the problem.
- If this would not be true, could you please add an exact description of the activities that still have to be done.
- If no further activities have to be done, could you please add a comment summarizing the result and close this issue.

**Comment by MartinSunal** [comment]
Change in OAS file PR https://github.com/openBackhaul/ApplicationPattern/pull/296  is done but it is not sufficient for this issue to move forward. It requires code changes which are tracked in issue https://github.com/openBackhaul/ApplicationPattern/issues/327 

Then we can make changes to these endpoints:
/v1/redirect-topology-change-information
/v1/register-yourself
/v1/embed-yourself

to implement new logic:
If the incoming application-name doesn't match LTP http-client/application-name that connects to the mapped forwardingConstruct, the LTP http-client/application-name must be updated based on the incoming request.
If the referenced httpClient does  not exist yet, it must be created with the stated uuid.

Mapping of endpoint and forwardingConstruct:
<html>
<body>


service name | forwarding construct
-- | --
/v1/redirect-topology-change-information | PromptForRedirectingTopologyInformationCausesSendingAnInitialStateToALT
/v1/register-yourself | PromptForRegisteringCausesRegistrationRequest
/v1/embed-yourself | PromptForBequeathingDataCausesRequestForBroadcastingInfoAboutServerReplacement


</body>
</html>

**Comment by openBackhaul** [comment]
(ForwardingConstruct _PromptForRedirectingTopologyInformationCausesSendingAnInitialStateToALT_ does not exist anymore, since we were solving a hen and egg problem by putting the LTP information into the ResponseBody of _/v1/redirect-topology-change-information_.)

Does this issue require refinement on the specification, or is it exclusively implementation related?
If exclusively implementation related, it shouldn't have milestone AP v2.0.0_spec, but AP v2.0.0_**impl**.

**Comment by openBackhaul** [comment]
[ApplicationPattern issue#454 _Handling of Semantics inside UUIDs_](https://github.com/openBackhaul/ApplicationPattern/issues/454) is proposing a general ruling for dealing with UUIDs.
Is this solving the underlying problem to this issue?

**Comment by openBackhaul** [comment]
Processing must be based on attributes' values.
New example: After RO addressed _ALT://regard-application_, ALT has to send _newApplication://v1/redirect-topology-change-information_.

1st Problem: How does ALT know that _/v1/redirect-topology-change-information_ is the correct operation name?
Answer: ALT doesn't know this for sure. 
ALT just knows the ApplicationPattern as it was at the design time of the ALT.
If the ApplicationPattern would have changed in regard of _/v1/redirect-topology-change-information_ since design of currently running ALT, embedding would fail in its first attempt.
But during the embedding process, the new application initiates a broadcast about updated OperationClients.
This broadcast results in RO addressing _ALT://v1/update-operation-client_.
And _/v1/update-operation-client_ contains the correct operation name that is replacing former _/v1/redirect-topology-change-information_.

2nd Problem: How does ALT know in which OperationClient the operation-name attribute is to be replaced?
- ALT has to search its list of LTPs for a TcpClient that holds the values of _application-name_ and _release-number_ according to the _application-name_ and _application-release-number_ attributes of the RequestBody of the _ALT://v1/update-operation-client_.
- In case of match, ALT has to search the list of clientLtps for an OperationClient that holds a value of _operation-name_ according to the _old-operation-name_ attribute of the RequestBody of the _ALT://v1/update-operation-client_.
- The _operation-name_ attribute of this OperationClient is to be replaced by the value of the _new-operation-name_ attribute of the RequestBody of the _ALT://v1/update-operation-client_.

**Comment by openBackhaul** [comment]
Specification part cover in [AP pull-request#469](https://github.com/openBackhaul/ApplicationPattern/pull/469).
Milestone changed to v2.0.0_impl.
