### ISSUE TITLE
Elasticsearch Javascript API unsupported fields

### ISSUE THREAD

**Issue by MartinSunal** [openBackhaul/ApplicationPattern#473]
Service policy definition in  ApplicationPattern.yaml contains fields 'timeout' and 'master-timeout'. While they are supported through Elasticsearch [REST API](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/ilm-put-lifecycle.html) they are not supported through [Elasticsearch Javascript client](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/7.17/api-reference.html#_ilm_putlifecycle).

Suggestion:
- remove query parameters "timeout" and "master-timeout" from service record policy definition

**Comment by PrathibaJee** [comment]
**My understanding :**
From the reference link mentioned in your comment to the Elastic search documentation , I can able to understand that , 
- "master-timeout" and "timeout" are optional query parameters that are useful while using the REST API of a Elastic search instance.
- Since , we are using the JS library "@elastic/elasticsearch": "~7.17.0"  , this query parameters is not required for us.

So , you are proposing to remove the "timeout" and "master-timeout" attributes from the service record policy definition in the operations , 
1. getControlConstruct
2. putElasticsearchClientServiceRecordsPolicy, 
3. getElasticsearchClientServiceRecordsPolicy

**Proposal :**
As per the definition , **the parameters "master-timeout" and "timeout" are defined as optional** and not "required".
Since the parameters "master-timeout" and "timeout" are optional , it will **not harm the request/response validation of the server if we dont include them in the requestBody or responseBody.** 
Additionally , I have the following views , 
- in the response of getControlConstruct and getElasticsearchClientServiceRecordsPolicy these attributes shall not be included
- in the requestBody of putElasticsearchClientServiceRecordsPolicy , since there is no need for this attribute , for now , no one will try to configure this value.

**So , shall we consider removing these attributes "master-timeout" and "timeout" in version 3.0.0 as the need/priority is low.**
Kindly please let me know if you have a different view.

**Comment by openBackhaul** [comment]
OAS: parameters "master-timeout" and "timeout" to be deleted from the ElasticsearchClient
