### ISSUE TITLE
Add 405 Method not Allowed status 

### ISSUE THREAD

**Issue by DanaSunal** [openBackhaul/ApplicationPattern#632]
Based on openBackhaul/ApplicationLayerTopology#253 

operationId: getElasticsearchClientServiceRecordsPolicy
operationId: putElasticsearchClientServiceRecordsPolicy

need to add 405 Method Not Allowed as one of the responses.

**Comment by DanaSunal** [comment]
After discussion with @IswaryaaS and some research I would suggest the code to be 501 Not Implemented. 4xx codes indicate that there is something wrong with the request, whereas 5xx indicate problem on server-side (or that the request itself is fine). 
- 404 is a bit too generic and it indicates that the functionality is there, but can be reached via different URI
- 405 means that wrong HTTP method was used for the request
Thoughts? @PrathibaJee

**Comment by PrathibaJee** [comment]
Thanks for the details @DanaSunal .
Since , in ALT both getElasticsearchClientServiceRecordsPolicy, putElasticsearchClientServiceRecordsPolicy services will not be implemented , 501 Not Implemented response code will fit for this scenario. yes , kindly please proceed.

One question, should this problem be solved in ApplicationLayerTopology application? If so , please close it here and raise a new issue there (or) use this issue https://github.com/openBackhaul/ApplicationLayerTopology/issues/253. Thanks.

**Comment by PrathibaJee** [comment]
If we are planning to include this services getElasticsearchClientServiceRecordsPolicy, putElasticsearchClientServiceRecordsPolicy  in ALT, and to leave it unimplemented.
then, 
yes, we shall respond with response code 501:Not implemented. 

In the specification , for the responses of each API , there is a "**default**" response code. For OamServices , all the errored responses are mapped to '#/components/responses/responseForErroredOamRequests'
This suffice the server side code to respond with the response code 501.
![image](https://github.com/openBackhaul/ApplicationPattern/assets/62344562/7ec1052f-6da5-4929-a1c7-eb261e0c4b3d)
Server side test sample as below,
![image](https://github.com/openBackhaul/ApplicationPattern/assets/62344562/8c8f228e-3d76-467c-a212-68c437b3c3fa)

Since this response code 501 is very specific to this two APIs and we can handle this scenario with the already existing "default" response code , proposing to not make any changes to the OAS.

@DanaSunal , kindly let me know your feedback, Thanks.

**Comment by openBackhaul** [comment]
**Required change to the OAS:**
Entire _/core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol=0/elasticsearch-client-interface-1-0:elasticsearch-client-interface-pac/elasticsearch-client-interface-configuration/service-records-policy:_ path to be deleted from the specification.

**Comment by openBackhaul** [comment]
Path has been deleted from the specification in case it is not implemented. 501 not required.
