### ISSUE TITLE
Checking filepath validity with regular expression

### ISSUE THREAD

**Issue by DanaSunal** [openBackhaul/ApplicationPattern#646]
We can use this 
`(\/.*|[a-zA-Z]:\\(?:([^<>:"\/\\|?*]*[^<>:"\/\\|?*.]\\|..\\)*([^<>:"\/\\|?*]*[^<>:"\/\\|?*.]\\?|..\\))?)`
regular expesssion to check the validity of file path.

Tested with windows and linux path: [Regex](https://regexr.com/7c0vi)

**Comment by IswaryaaS** [comment]
In putFileProfileFilePath, the attribute "file-profile-1-0:file-path" is not having any constraint. This would allow any invalid file-name to be configured to file-profile of an application. 

Including a Regex pattern to **putFileProfileFilePath**, would restrict any invalid configuration to any application. 

Reason: Since, application-data is accessed through the file-path configured in file-profile, any invalid file name would fail accessing application-data from application which may lead to functional failure.

**Comment by openBackhaul** [comment]
**Decision during the ImplementersCall on 14th of April 2023:**

**ApplicationPattern:**
- OAS: The path /core-model-1-4:control-construct/profile-collection/profile={uuid}/file-profile-1-0:file-profile-pac/file-profile-configuration/file-path: to be changed towards ../file-name.
- OAS: A pattern that is restricting on bare file names (without path) is to be added.
- ProfileList to be adapted
- ProfileInstanceList to be adapted
- CONFIGfile to be adapted

Same Issue to be opened at: 
- RegistryOffice
- TypeApprovalRegister
- AdministratorAdministration
