### ISSUE TITLE
EATL  and OL List record  related testcases are failing 

### ISSUE THREAD

**Issue by ManasaBM1** [openBackhaul/ApplicationPattern#658]
**Issue Description :** 

In test suite , as part of  testing Basic services or Individual services for  forwardings triggered , update-ltp notified , request notified we send request to EaTL  /v/1ist-records-of-flow and for OAM related services we send request to OL /v1/list-records-of-application where we will be testing the particular forwarding is sent or not  by fetching the related records.

These testcases are failing when we run test-suite against applications.

**Observation :** 
Records are being fetched correctly as per expectation . But still the test assertions are failing and test-cases are also intact and no bug found .

**Comment by IswaryaaS** [comment]
in input load file, we have userName value with some trailing spaces. but while reaching server those spaces are trimmed (may be from openApi interface), so because of this difference between username of input load file which is used in test-suite and username logged by application .. the testcases are failing. 
This can be solved by updating a valid username in input load-file in pipeline.
