### ISSUE TITLE
Support backendTime response header for ElasticSearch interaction

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#659]
Individual and Basic services consists of a response header parameter called backendTime.
As per the specification , this parameter should report the time elapsed for data retrieval from the backend (service invocation, database access…). Expressed in milliseconds.
Earlier in version 1 of the ApplicationPattern(AP) , we don’t have a database connected and all we had is a flat JSON file. 
Since , we have ElasticSearch(ES) integrated with the ALT, EATL and OL application , for every service , 
- the time spent in interacting with the ES shall be calculated and included in this header.
- If there are multiple interactions to ES, the consolidated time spent shall be included to this header
- If there is no interaction to ES , then this shall be 0 

(Individual services in ALT, EATL and OL application shall also requires updation to support this functionality)

**Comment by DanaSunal** [comment]
Analysis:
In order to have backend-time information in response header, following needs to be done:
- General handling
- [ ] ResponseHeader class needs 'backendTime' as argument (default value = 0)
- Query requests handling
- [ ] all Elasticsearch query methods in service classes need to be checked for filtering of data and add key "took" (see [ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-your-data.html)) to be returned from ES response
- [ ] all controller methods calling these service methods need to strip the "took" key/value from service method response and add it to response header
- Other requests handling
Elasticsearch only returns the "took" key when the request is a query. I was unable to find such information when eg. adding a new document to index. Therefore my proposal is:
- [ ] all Elasticsearch requests that are not queries should start a timer before the request to ES is sent and stop the timer after response is received. Add this time to the json response under key "took" (to unify the handling in controller).

Each service class is responsible to sum up the backendTimes if there are multiple ES requests. Each controller class is responsible for stripping the "took" key from the response and add it to response header.

@PrathibaJee  Let me know your thoughts before I start implementing.

Overall effort should not exceed 2MD as a lot of the code will be repetitive, it's just in a lot of places/applications.

**Comment by PrathibaJee** [comment]
Thank you for the detailed analysis. 
So , for the query requests, from ES itself we shall able to get the time spent value whereas for Create, Update, delete, this needs to be handled in our application side.
Since ElasticSearch is new to our environment , the 'backendTime' header parameter will be useful to narrow down performance related issues. Kindly please let me know whether 2MD includes the linked issues aswell https://github.com/openBackhaul/ApplicationLayerTopology/issues/297, https://github.com/openBackhaul/ExecutionAndTraceLog/issues/215, https://github.com/openBackhaul/OamLog/issues/204 ?

**Comment by DanaSunal** [comment]
> So , for the query requests, from ES itself we shall able to get the time spent value whereas for Create, Update, delete, this needs to be handled in our application side.
Yes, exactly.
It includes the linked issues as well, the logic will be the same.

**Comment by PrathibaJee** [comment]
> Since ElasticSearch is new to our environment , the 'backendTime' header parameter will be useful to narrow down performance related issues.

Kindly please proceed. Many thanks.
