### ISSUE TITLE
/v1/ltp-update is recorded in EATL twice if the response is 500

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#801]
If the /v1/ltp-update is not successful and if the responseCode is 500 , then , the result is logging in both server and the client side resulting in two entries in the EATL application , 

example :

{
    "x-correlator": "590e8400-e11b-11d4-a716-446655440817",
    "trace-indicator": "1.2",
    "user": "User Name",
    "originator": "AdministratorAdministration",
    "application-name": "ApplicationLayerTopology",
    "release-number": "2.0.1",
    "operation-name": "/v1/update-ltp",
    "response-code": 500
  },
  {
    "x-correlator": "590e8400-e11b-11d4-a716-446655440817",
    "trace-indicator": "1.2",
    "user": "User Name",
    "originator": "AdministratorAdministration",
    "application-name": "ApplicationLayerTopology",
    "release-number": "2.0.1",
    "operation-name": "/v1/update-ltp",
    "response-code": 500,
    "timestamp": "2023-07-08T06:21:02+00:00",
    "stringified-body": "{\"uuid\":\"aa-2-0-1-http-c-ro-2-0-1-000\",\"ltp-direction\":\"core-model-1-4:TERMINATION_DIRECTION_SINK\",\"client-ltp\":[\"aa-2-0-1-op-c-bm-ro-2-0-1-000\",\"aa-2-0-1-op-c-bm-ro-2-0-1-001\",\"aa-2-0-1-op-c-bm-ro-2-0-1-002\",\"aa-2-0-1-op-c-bm-ro-2-0-1-003\",\"aa-2-0-1-op-c-im-ro-2-0-1-000\",\"aa-2-0-1-op-c-im-ro-2-0-1-001\",\"aa-2-0-1-op-c-im-ro-2-0-1-002\",\"aa-2-0-1-op-c-im-ro-2-0-1-004\"],\"server-ltp\":[\"aa-2-0-1-tcp-c-ro-2-0-1-000\"],\"layer-protocol\":[{\"local-id\":\"0\",\"layer-protocol-name\":\"http-client-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_HTTP_LAYER\",\"http-client-interface-1-0:http-client-interface-pac\":{\"http-client-interface-configuration\":{\"application-name\":\"RegistryOffice\",\"release-number\":\"4.1.0\"}}}]}"
  }

> Priority:Low;

**Comment by DanaSunal** [comment]
Moved this to ApplicationPattern as this is a generic issue for all callbacks, not just update-ltp. Any callback resulting in 500 would be logged twice.

The problem here is, that axios call in [RequestBuilder.BuildAndTriggerRestRequest](https://github.com/openBackhaul/ApplicationPattern/blob/develop/server/applicationPattern/applicationPattern/rest/client/RequestBuilder.js)  throws an error if the response has status code other than 2xx. This activates catch block and since the returned error contains response, this is just returned back. Hence in eventDispatcher we cannot differentiate if the 500 was a normal return code or an error code returned from axios because something happened.

I updated error handling according to axios doc: [https://axios-http.com/docs/handling_errors](https://axios-http.com/docs/handling_errors)  and set 408 (Request Timeout) as the response code to be set, when an axios error occurs.

IMHO 404 (what it was previously) is not good, because according to our openAPI, 404 is a valid response, which means, we would be still having this exact issue.

I also customized the logging to console, because it should only be necessary when the unexpected happens.
