### ISSUE TITLE
OAS: /v1/update-operation-key requires old-operation-key

### ISSUE THREAD

**Issue by MartinSunal** [openBackhaul/ApplicationPattern#90]
**Describe the bug**
Operation /v1/update-operation-key of each application requires body like:
- new-operation-key
- old-operation-key
- operation-uuid

but OKM sends only:
- new-operation-key
- operation-uuid

since it does not know (store) old operation key for every operation.

**Solution and/or next step(s)**  
Operation /v1/update-operation-key should require body with:
- new-operation-key
- operation-uuid

**Comment by openBackhaul** [comment]
The /v1/update-operation-key :: old-operation-key attribute must be deleted, because OperationKeyManagement application cannot know its value.
It must be removed with the next release of the specification

**Comment by openBackhaul** [comment]
It is already fixed in the latest ApplicationPattern specification 1.0.0_spec.
If the /v1/update-operation-key :: old-operation-key attribute would still be contained in the ApplicationPattern implementation, which is base of the OKM, this would mean that the ApplicationPattern specification has been changed after it became base of the latest implementation.
This is not ideal in regards of version management, but we are on our way to improve.
Anyway, this issue could be closed.
