### ISSUE TITLE
Application Pattern implementation : application-name attribute update among services

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#92]
In application pattern , there are few basic services which deals with subscription of core-applications to an applications.

Due to an expected update in specification for those services where the description of application-name attribute to be changed from "find or create" to "find" for the actual application involved, the Application Pattern package implementation needs an update for the below mentioned services:
- /v1/register-yourself (registry-office-application = RegistryOffice)
- /v1/embed-yourself (registry-office-application = RegistryOffice)
- /v1/inquire-oam-request-approvals (oam-approval-application = AdministratorAdministration)
- /v1/redirect-topology-change-information (topology-application = ApplicationLayerTopology)

Related issue: #91

**Comment by PrathibaJee** [comment]
To make sure the incoming application names are in sync with the existing applications in the CONFIG file , there is a logical change required in the server side.
All the subscription for notification services related to basic services maintains an invariant forwarding-construct.

For example , the following basic services are mapped to the corresponding invariant forwardingConstruct.

| service name | forwarding construct |
| ------------- |:-------------:|
| /v1/redirect-service-request-information | ServiceRequestCausesLoggingRequest |
| /v1/redirect-oam-request-information | OamRequestCausesLoggingRequest |
| /v1/inquire-oam-request-approvals | OamRequestCausesInquiryForAuthentication |
| /v1/redirect-topology-change-information | PromptForRedirectingTopologyInformationCausesSendingAnInitialStateToALT |
| /v1/register-yourself | PromptForRegisteringCausesRegistrationRequest |
|/v1/embed-yourself | PromptForBequeathingDataCausesRequestForBroadcastingInfoAboutServerReplacement |
 
The http-client/application-name that connects to the mapped forwardingConstruct’s must be used to validate the incoming application’s name.
Also , when there is a change to the http-client/application-name using a OAM PUT request , the latest application name can be considered for validation without additional logic.

**Comment by PrathibaJee** [comment]
The [proposal](https://github.com/openBackhaul/ApplicationPattern/issues/92#issuecomment-1254966082) looks very clear and understandable. Thanks.

So , based on the description of the "application-name" , further processing should happen.

- If the description starts with "find" , then the validation is strict and further processed only if the incoming application-name matches the http-client/application-name that connects to the mapped forwardingConstruct 

- If the description starts with "find or create" , then if the incoming application-name does'nt match the http-client/application-name that connects to the mapped forwardingConstruct , the http-client/application-name will be updated based on the incoming request.
Just one clarification required in this regard , does'nt the prefix should be **"find or update" instead of "find or create"** as the existing application-name will be updated by the new one.

**Comment by MartinSunal** [comment]
Behavior of "find" has been fixed in https://github.com/openBackhaul/ApplicationPattern/pull/278 for these endpoints:
- /v1/redirect-service-request-information
- /v1/redirect-oam-request-information
- /v1/inquire-oam-request-approvals

Behavior of "find and create" can be fixed after other applications adopt changes made in [Add PUT to OAM of application-name](https://github.com/openBackhaul/ApplicationPattern/pull/296). Fixing of "find and create" is tracked in https://github.com/openBackhaul/ApplicationPattern/issues/300
